version: '3.8'

services:
  # Development frontend with hot reload
  umkm-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - umkm-network

  # PostgreSQL for local development
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umkm_platform_dev
      POSTGRES_USER: umkm_user
      POSTGRES_PASSWORD: umkm_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - umkm-network

volumes:
  postgres_dev_data:

networks:
  umkm-network:
    driver: bridge